version: "3.9"

services:

  grobid:
    image: lfoppiano/grobid:0.8.1
    container_name: retrieval-grobid
    environment:
      JAVA_TOOL_OPTIONS: -XX:-UseContainerSupport
    ports:
      - "8070:8070"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/api/isalive"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
